openapi: 3.2.0
info:
  title: Currency Exchange (Sandbox) Providers API
  description: 'A sandbox version of the Currency Exchange Rate API. This API provides a standard set of exchange rates for Beazley systems.


    Please contact

    ITArchitecture@Beazley.com if you have any questions about this API.'
  version: '1.0'
servers:
- url: https://api.beazley.com/sandbox/fx/v1
security:
- apiKeyHeader: []
- apiKeyQuery: []
tags:
- name: Providers
paths:
  /providers:
    get:
      summary: Providers
      operationId: 56d088f797fe1e081ca252eb
      responses:
        '200':
          description: ''
          content:
            application/json:
              example:
              - Id: 1
                Code: boe
                Name: Bank of England
              - Id: 2
                Code: oan
                Name: Oanda
            text/xml:
              example: <ArrayOfProvider xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/Beazley.FX.WebService.Models.FX"> <Provider> <Code>boe</Code> <Id>1</Id> <Name>Bank of England</Name> </Provider> <Provider> <Code>oan</Code> <Id>2</Id> <Name>Oanda</Name> </Provider> </ArrayOfProvider>
      tags:
      - Providers
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
